### ISSUE TITLE
Migrate to discord.py rewrite.

### ISSUE THREAD

**Issue by heavysaturn** [RLBot/discord-bot#2]
It's smarter, better organised, more stable, and faster, and the branch you're currently running will soon be deprecated.

You can use [this migration guide](https://discordpy.readthedocs.io/en/rewrite/migrating.html) to do the migration. A cog-based bot setup is ideal.

**Comment by skyborgff** [comment]
I'll make this my top priority in the bot before adding anything else

**Comment by heavysaturn** [comment]
I could probably contribute some code towards this myself. It's familiar ground to me, and I think your bot ought to graduate to a proper multi-file layout anyway. single-file bots quite frankly are a mess to work with.

**Comment by skyborgff** [comment]
I would gladly accept pull requests :)
I didn't think the bot was big enough to deserve that graduation. My RLBot as 600+ lines in only 2 files, so i'm quite the filesaver person myself

**Comment by heavysaturn** [comment]
well, a cog-based layout with rewrite requires more than one file anyway, and it's just a very clean way to represent the bot. it scales really well and you're usually not working in a file where there's a lot of scrolling involved. It's easy on the eyes. 

**But**; this requires that you have tools that accommodate a project with many files while you're doing the development. If you guys are doing IDLE, I may commence transfenestration. a good editor like VSCode, Atom or SublimeText, or an IDE like PyCharm will make multi-file structures a real joy to work with, though.

Of course, ultimately this is down to preference. I will admit that I may prefer multi file structures because I am so used to them. It's like.. big boy programming. :P

**Comment by skyborgff** [comment]
I do have pycharm, and i've been trying to get more proficient at using it.
Only goosefairy uses IDLE XD
Multi file structures aren't my first choice, as i'm not an experienced dev and had not the time to mature those skills. although i'm investing in that kind of structure, for example, for my RLBot rewrite

**Comment by cominixo01** [comment]
I can help with this, I have a lot of experience with discord.py rewrite + cogs

**Comment by skyborgff** [comment]
> I can help with this, I have a lot of experience with discord.py rewrite + cogs

I would be glad to have your help :)

**Comment by heavysaturn** [comment]
This was solved in #4
